import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Lamao Pizza | Fresh & Delicious Pizza",
  description: "Lamao Pizza serves delicious, freshly made pizza with easy online ordering. Explore our menu and order your favorite pizza today.",
  verification: {
    google: "gcgKMb6l5xFfXFI2Wd7eLpSIaK8EgQVQB-rdut_293k",
  },
};


import Header from "../component/Header";
import Footer from "../component/Footer";
// import featured from "./(pizzalist)/featured/page";
import { CartProvider } from "../context/CartContext";
// import CartProvider

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <div className="layout">
          <CartProvider>
          <Header />
            <main>
              {children}
            </main>
          <Footer />
          </ CartProvider>
        </div>

      </body>
    </html>
  );
}
